version: '3'
services:
  backend:
    image: 'amitlubin/attendance-backend:latest'
    restart: always
    depends_on:
      - mysql
    env_file:
      - environmentals/.env
    # ports: 
    #  - "5000:5000"
    # environment:
    #   - MYSQL_HOST=mysql
    
  
  mysql:
    image: 'mysql:8'
    env_file:
      - environmentals/.env
    restart: always
    hostname: mysql
    # ports:
    #   - "3306:3306"

  frontend:
    image: 'amitlubin/attendance-frontend:latest'
    depends_on:
      - backend
    env_file:
      - environmentals/.env
    #ports:
    #  - "3000:3000"

  nginx:
    image: 'amitlubin/attendance-nginx:latest'
    restart: always
    ports:
      - '4000:80'