version: '3'
services:
  backend:
    image: 'amitlubin/attendance-backend:latest'
    restart: always
    env_file:
      - environmentals/.env
    depends_on:
      - mysql
    #ports: 
    #  - "5000:5000"
  
  mysql:
    image: 'mysql:latest'
    env_file:
      - environmentals/.env
    restart: always

  frontend:
    image: 'amitlubin/attendance-frontend:latest'
    depends_on:
      - backend
    #ports:
    #  - "3000:3000"

  nginx:
    image: 'amitlubin/attendance-nginx:latest'
    restart: always
    ports:
      - '4000:80'